### PR TITLE
Debug Jenkins Bundler::Definition issue

### PR DESCRIPTION
**Pull request by garettarrowood**
This added condition fixes a bug with a change in behavior in `::Bundler::Definition` in Jenkins CI.

### CODE REVIEW

**Comment by benlangfeld** [comment]
And of course we don't have a changelog yet, but we should :)

**Comment by garettarrowood** [comment]
How to test exactly?  Mock Bundler::Definition?

**Comment by benlangfeld** [comment]
> How to test exactly? Mock Bundler::Definition?

Preferably figure out why Bundler gives us the result it does and simulate the conditions that cause it.

**Comment by benlangfeld** [comment]
> Is best practice to get this squared away/merged, then raise version on a single commit directly to master?

Yes :)

**Comment by garettarrowood** [comment]
--- Version raise removed ---

**Pull request merged**
